import styles from "./LegalRegulatoryPage.module.css";

const termsData = {
  legalCompliance:
    "While we strive to provide accurate and reliable tools, it is important to note that MoneyReload is not a registered financial service or advisory platform. We are not licensed or regulated by any financial authority or government body in India.",
  disclaimer:
    "The calculators provided on this website are for educational and informational purposes only. The results generated by our calculators are estimates based on the data you provide and the assumptions made in the calculation models. They are not intended to be a substitute for professional financial advice. We recommend that you seek advice from a certified financial advisor or tax consultant before making any major financial decisions. We do not assume responsibility for any financial consequences, including profits or losses, arising from the use of the information or results generated by our website.",
  regulatoryOversight:
    "Although we are not subject to financial regulatory oversight, we aim to comply with relevant privacy and data protection laws in India, including but not limited to the Information Technology Act, 2000, and any applicable amendments.",
  disputeResolution:
    "Any disputes related to the use of this website will be governed by the laws of India. In the event of a dispute, we encourage you to contact us first so we may attempt to resolve the matter amicably. Should legal action be necessary, it will be conducted in the courts of Mumbai, India.",
  changesToLegal:
    "We reserve the right to update or modify our legal and regulatory terms at any time. We will notify users of significant changes via updates posted on this page.",
  contactUs:
    "Feel free to reach out to us for any inquiries, feedback, or support.",
};

const LegalRegulatoryPage = async () => {
  return (
    <div className={styles.container}>
      <div className={styles.section}>
        <h3>Legal Compliance</h3>
        <p>{termsData.legalCompliance}</p>
      </div>

      <div className={styles.section}>
        <h3>Disclaimer</h3>
        <p>{termsData.disclaimer}</p>
      </div>

      <div className={styles.section}>
        <h3>Regulatory Oversight</h3>
        <p>{termsData.regulatoryOversight}</p>
      </div>

      <div className={styles.section}>
        <h3>Dispute Resolution</h3>
        <p>{termsData.disputeResolution}</p>
      </div>

      <div className={styles.section}>
        <h3>Changes to Legal & Regulatory</h3>
        <p>{termsData.changesToLegal}</p>
      </div>
      <div className={styles.section}>
        <h3>Contact Us</h3>
        <p>{termsData.contactUs}</p>
        <p>
          Email:{" "}
          <a href="mailto:contact@moneyreload.com">contact@moneyreload.com</a>
        </p>
      </div>
    </div>
  );
};

export default LegalRegulatoryPage;
